AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3.3

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/PredicateName:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/WordArray:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/Documentation:
  Severity: warning

Style/EachWithObject:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Alias:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 180

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Performance/Casecmp:
  Enabled: false
